name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
#  url_launcher: ^0.4.2
  flutter:
    sdk: flutter
#  sms: ^0.2.0
#  flutter_twilio_voice: ^0.0.3
  http: ^0.12.0+2
#  flutter_email_sender: ^2.1.0
#  flutter_mailer: ^0.4.1+1

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_tagging: ^1.1.0
  url_launcher: ^5.2.5
  get_it: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
